На клиентской части Чат записывается в редакс и выводится в окне
sla6ak/world-future pull request #26
Opened 2023-01-18 19:40 UTC by Aleksandr-Pod

2023-01-18 22:40 UTC, sla6ak requested changes

2023-01-18 22:40 UTC, sla6ak commented on src/Redux/Slises/chatGameSlise.js
> -    mySMSAction(_state, action) {
а что если сообщение не дошло до сервера мы не должны записывать его сразу на клиенте. мы отправим подождем пока сервер сохранит а потом перезапишим в стейт ответ сервера... и тут не более N сообщений хранить до сотни. всеравно никто листать не будет...

2023-01-18 23:39 UTC, sla6ak approved these changes

2023-01-18 23:39 UTC, merged

2023-01-19 07:46 UTC, Aleksandr-Pod commented on src/Redux/Slises/chatGameSlise.js
> -    mySMSAction(_state, action) {
Это был как тестовый вариант и до того, как я разобрался с хуком отправки сообщений на сервер.
Вторым этапом планировал отправлять сообщение на сервер а в ответ с сервера придёт всем юзерам сообщение с этим чатом, тогда и записывать его в редакс.